from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class DatasetParameters(BaseModel):
    date_from: Optional[datetime] = None
    date_to: Optional[datetime] = None
    LOB: Optional[str] = None
    filters: dict[str, Any] = Field(default_factory=dict)
    sample_size: Optional[int] = None


class PromptManagement(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    prompt_title: str = Field(..., description="Title of the prompt")
    version: int = 1
    parent_version_id: Optional[UUID] = None  # lineage

    # Prompt content
    inital_user_prompt_request:str = Field(...,description='The users prompt for prompt generator to build a tool')
    generated_system_prompt: str = Field(...,descriptio='Prompt Generated by prompt generator to address the users issue')
    generated_user_prompt: str = Field(...,descriptio='Prompt Generated by prompt generator to address the users issue')
    output_format: dict[str, Any] = Field(default_factory=dict)
    metadata_fields: List[str] = Field(default_factory=list)
    saved_location_of_prompt: Optional[str] = None

    # Context
    lob: List[str] = Field(default_factory=list)
    model: str = ""
    temperature: Optional[float] = None

    # Schema (populated after schema generation)
    schema_definition: dict[str, Any] = Field(default_factory=dict)
    schema_model_name: Optional[str] = None
    schema_path: Optional[str] = None

    # Evaluation (populated after evaluation)
    evaluation_scores: dict[str, Any] = Field(default_factory=dict)

    # Dataset
    dataset_parameters: DatasetParameters = Field(default_factory=DatasetParameters)

    # Timestamps
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)
